version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:${NGINX_PROXY_TAG}
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html

  nginx-gen:
    image: jwilder/docker-gen:${NGINX_GEN_TAG}
    container_name: nginx-gen
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/data/templates:/etc/docker-gen/templates:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx_proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  lets-encrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:${LETS_ENCRYPT_COMPANION_TAG}
    container_name: nginx_proxy-lets_encrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
      - nginx-gen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  redis:
    image: redis:${REDIS_TAG}
    container_name: redis
    volumes:
      - ./redis:/data
    expose:
      - 6379

  nextcloud-db:
    image: mariadb:${MARIADB_TAG}
    env_file: .nextcloud-db.env
    volumes:
      - ./nextcloud/db-data:/var/lib/mysql
    expose:
      - 3306

  nextcloud:
    image: wonderfall/nextcloud:${NEXTCLOUD_TAG}
    env_file: .nextcloud.env
    depends_on:
      - nextcloud-db
      - redis
    volumes:
      - ./nextcloud/data:/data
      - ./nextcloud/config:/config
      - ./nextcloud/apps:/apps2
      - ./nextcloud/themes:/nextcloud/themes
    expose:
      - 8888
